### User login
POST http://localhost:8180/realms/kdg-realm/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=backend-app&username=kiki@gmail.com&password=password

### New user login
POST http://localhost:8180/realms/kdg-realm/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=backend-app&username=koko@gmail.com&password=password

