### User login
POST http://localhost:8180/realms/kdg-realm/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=backend-app&username=kiki@gmail.com&password=password

### Create new restaurant
POST http://localhost:8080/restaurants
Content-Type: application/json
Accept: application/json

{
  "ownerId": "d82cecfb-3201-4545-812d-542ed4feea92",
  "name": "Tasty Sushi",
  "address": {
    "street": "Main Street",
    "number": "12A",
    "city": "Brussels",
    "zipcode": "1000",
    "country": "Belgium"
  },
  "email": "tasty@sushi.com",
  "pictures": [
    "http://example.com/sushi1.jpg",
    "http://example.com/sushi2.jpg"
  ],
  "cuisineType": "JAPANESE",
  "preparationTime": 20.5,
  "openingHours": [
    {
      "dayOfWeek": "MONDAY",
      "openingTime": "09:00",
      "closingTime": "21:00"
    },
    {
      "dayOfWeek": "TUESDAY",
      "openingTime": "09:00",
      "closingTime": "21:00"
    }
  ]
}

### Create a new dish draft
POST http://localhost:8080/restaurants/fccd6c86-bb4d-4423-a3f7-d193aa3543f2/dishes/draft
Content-Type: application/json

{
  "dishId": null,
  "name": "Margherita Pizza",
  "dishType": "MAIN",
  "foodTags": ["GLUTEN", "LACTOSE"],
  "description": "Classic pizza with tomato and cheese",
  "price": 12.5,
  "imageUrl": "http://example.com/pizza.jpg"
}

### Update existing dish draft
POST http://localhost:8080/restaurants/fccd6c86-bb4d-4423-a3f7-d193aa3543f2/dishes/draft
Content-Type: application/json

{
  "dishId": "73cf013c-d224-4fb5-8f50-286b99d20136",
  "name": "Margherita Pizza Deluxe",
  "dishType": "MAIN",
  "foodTags": ["VEGAN"],
  "description": "Upgraded version with extra mozzarella.",
  "price": 11.49,
  "imageUrl": "https://example.com/pizza-deluxe.jpg"
}

### Publish dish
POST http://localhost:8080/restaurants/fccd6c86-bb4d-4423-a3f7-d193aa3543f2/dishes/73cf013c-d224-4fb5-8f50-286b99d20136/publish

### Unpublish dish
POST http://localhost:8080/restaurants/fccd6c86-bb4d-4423-a3f7-d193aa3543f2/dishes/73cf013c-d224-4fb5-8f50-286b99d20136/unpublish

### Mark dish out of stock
POST http://localhost:8080/restaurants/fccd6c86-bb4d-4423-a3f7-d193aa3543f2/dishes/73cf013c-d224-4fb5-8f50-286b99d20136/out-of-stock

### Mark dish back in stock
POST http://localhost:8080/restaurants/fccd6c86-bb4d-4423-a3f7-d193aa3543f2/dishes/73cf013c-d224-4fb5-8f50-286b99d20136/in-stock

### Create a new dish draft
POST http://localhost:8080/restaurants/fccd6c86-bb4d-4423-a3f7-d193aa3543f2/dishes/draft
Content-Type: application/json

{
  "dishId": null,
  "name": "Lasagna",
  "dishType": "MAIN",
  "foodTags": ["VEGAN", "GLUTEN"],
  "description": "Vegan lasagna with fresh basil.",
  "price": 12.99,
  "imageUrl": "https://example.com/lasagna.jpg"
}

### Create a new dish draft
POST http://localhost:8080/restaurants/fccd6c86-bb4d-4423-a3f7-d193aa3543f2/dishes/draft
Content-Type: application/json

{
  "dishId": null,
  "name": "Ham and Cheese Toast",
  "dishType": "STARTER",
  "foodTags": ["LACTOSE"],
  "description": "Classic toast with ham and cheese.",
  "price": 5.99,
  "imageUrl": "https://example.com/toast.jpg"
}

### Create a new dish draft
POST http://localhost:8080/restaurants/fccd6c86-bb4d-4423-a3f7-d193aa3543f2/dishes/draft
Content-Type: application/json

{
  "dishId": null,
  "name": "Cheese Toast",
  "dishType": "STARTER",
  "foodTags": ["LACTOSE"],
  "description": "Classic toast with cheese.",
  "price": 5.99,
  "imageUrl": "https://example.com/toast.jpg"
}

### Publish dish
POST http://localhost:8080/restaurants/fccd6c86-bb4d-4423-a3f7-d193aa3543f2/dishes/73cf013c-d224-4fb5-8f50-286b99d20136/publish

### Update existing dish live dish
POST http://localhost:8080/restaurants/fccd6c86-bb4d-4423-a3f7-d193aa3543f2/dishes/draft
Content-Type: application/json

{
  "dishId": "73cf013c-d224-4fb5-8f50-286b99d20136",
  "name": "Margherita Pizza Delux",
  "dishType": "MAIN",
  "foodTags": ["VEGAN", "LACTOSE"],
  "description": "New version with extra extra mozzarella.",
  "price": 15.49,
  "imageUrl": "https://example.com/pizza-deluxe.jpg"
}

### Apply all pending draft changes
POST http://localhost:8080/restaurants/fccd6c86-bb4d-4423-a3f7-d193aa3543f2/dishes/apply-drafts

### UPDATE OPENING HOURS
PUT http://localhost:8080/restaurants/fccd6c86-bb4d-4423-a3f7-d193aa3543f2/opening-hours
Content-Type: application/json

[
  {
    "id": "60341249-265f-481c-a74c-af81bcf75a50",
    "dayOfWeek": "MONDAY",
    "openingTime": "09:00",
    "closingTime": "17:00"
  },
  {
    "id": "5a6c2a6b-c7f7-46ce-921d-41991716e07c",
    "dayOfWeek": "TUESDAY",
    "openingTime": "09:00",
    "closingTime": "17:00"
  }
]

### MANUALLY OPEN THE RESTAURANT
PUT http://localhost:8080/restaurants/fccd6c86-bb4d-4423-a3f7-d193aa3543f2/status?status=OPEN

### MANUALLY CLOSE THE RESTAURANT
PUT http://localhost:8080/restaurants/fccd6c86-bb4d-4423-a3f7-d193aa3543f2/status?status=CLOSED

### RETURN TO AUTOMATIC MODE
PUT http://localhost:8080/restaurants/fccd6c86-bb4d-4423-a3f7-d193aa3543f2/status?status=AUTO